# Generated by Django 3.2.5 on 2021-07-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
