# Generated by Django 3.2.5 on 2021-07-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee',
            field=models.CharField(blank=True, choices=[('1', 'Looking for a job'), ('2', 'Posting job listings')], max_length=1, null=True),
        ),
    ]
