# Generated by Django 3.2.5 on 2021-07-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact_num',
            new_name='contact_number',
        ),
    ]
