# Generated by Django 3.2.5 on 2021-07-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_contact_num_user_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='user',
            name='contact_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
