# Generated by Django 3.2.5 on 2021-07-14 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=1500)),
                ('location', models.CharField(max_length=150)),
                ('job_type', models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Contract'), ('4', 'Internship')], max_length=1)),
                ('category', models.CharField(blank=True, choices=[('1', 'Frontend'), ('2', 'Backend'), ('3', 'Fullstack')], max_length=1)),
                ('compensation', models.CharField(choices=[('Salary', (('1', '<$40k'), ('2', '$40k-50k'), ('3', '$50k-60k'), ('4', '$60k-70k'), ('5', '$70k-80k'), ('6', '$80k-90k'), ('7', '90k-100k'), ('8', '100k+'))), ('Hourly', (('1', '<$20/hr'), ('2', '$20/hr-$25/hr'), ('3', '$25/hr-$30/hr'), ('4', '$30/hr-$35/hr'), ('5', '$35/hr-$40/hr'), ('6', '$40/hr-$50/hr'), ('7', '$50/hr+')))], max_length=1)),
                ('post_date', models.DateField(default='2021-07-14')),
                ('is_open', models.BooleanField(default=True)),
                ('applicants', models.ManyToManyField(related_name='listing_applicants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='listing_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
