# Generated by Django 3.2.5 on 2021-07-15 01:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='accepted_apps',
            field=models.ManyToManyField(related_name='progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='denied_apps',
            field=models.ManyToManyField(related_name='denied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='interviewing_apps',
            field=models.ManyToManyField(related_name='interviewing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='post_date',
            field=models.DateField(default='2021-07-15'),
        ),
    ]
