# Generated by Django 3.2.5 on 2021-07-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20210715_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='compensation',
            field=models.CharField(choices=[('Salary', (('1', '<$40k'), ('2', '$40k-50k'), ('3', '$50k-60k'), ('4', '$60k-70k'), ('5', '$70k-80k'), ('6', '$80k-90k'), ('7', '90k-100k'), ('8', '100k+'))), ('Hourly', (('9', '<$20/hr'), ('10', '$20/hr-$25/hr'), ('11', '$25/hr-$30/hr'), ('12', '$30/hr-$35/hr'), ('13', '$35/hr-$40/hr'), ('14', '$40/hr-$50/hr'), ('15', '$50/hr+')))], max_length=2),
        ),
    ]
