# Generated by Django 3.2.5 on 2021-07-19 02:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0004_listing_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='hired_apps',
            field=models.ManyToManyField(related_name='hired', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='offer_extended_apps',
            field=models.ManyToManyField(related_name='offered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='post_date',
            field=models.DateField(default='2021-07-19'),
        ),
    ]
